import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "infinitive Property Management ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
